pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        def azureToken = providers.gradleProperty("AZURE_PERSONAL_ACCESS_TOKEN").orNull
                ?: System.getenv("AZURE_PERSONAL_ACCESS_TOKEN")
        flatDir {
            dirs 'libs'
        }
        maven {
            name = 'SDK_UNICO'
            url = uri('https://pkgs.dev.azure.com/stndtef/SmartPOS/_packaging/SDK_UNICO@Release/maven/v1')

            credentials {
                username = 'stndtef'
                password = azureToken
            }
        }
        maven {
            name = 'SDK_UNICO_DEPENDENCIES'
            url = uri('https://pkgs.dev.azure.com/stndtef/SmartPOS/_packaging/SDK_UNICO@Dependencies/maven/v1')

            credentials {
                username = 'stndtef'
                password = azureToken
            }
        }
        google()
        mavenCentral()
    }
}

rootProject.name = "Paykit Test SDK Java"
include ':app'
