plugins {
    alias(libs.plugins.android.application)
}

def useLocalSdk = providers.gradleProperty("useLocalSdk")
        .map { it.toBoolean() }
        .orElse(false)
        .get()

def sdkPayServicesVersion = "2.2.0.+"

def flavors = [
        linxtef: 22,
        linxtefadyen: 28,
        linxtefgpos760: 22,
        linxtefgpos720: 22,
        stone: 22,
        pagseguro: 23,
        vero: 22,
        getnet: 22,
        rede: 28,
        cielo: 25,
        sicoob: 24,
        sitef: 22,
        gsurf: 26
]

android {
    namespace 'com.linx.paykit.demo'
    compileSdk 34

    defaultConfig {
        applicationId "com.linx.paykit.demo"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        if (useLocalSdk) {
            missingDimensionStrategy("providers", "linxtef")
            missingDimensionStrategy("edition", "full")
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    if (!useLocalSdk) {
        flavorDimensions "providers"
        productFlavors {
            flavors.each { flavorName, flavorMinSdk ->
                create(flavorName) {
                    dimension "providers"
                    minSdk flavorMinSdk
                }
            }
        }
    } else {
        flavorDimensions += ['providers', 'tefDevice']
        productFlavors {
            create("linxtef") {
                dimension = "providers"
            }
            create("cielo") {
                dimension = "providers"
                minSdk = 24
                targetSdk = 29
            }
            create("stone") {
                dimension = "providers"
                minSdk = 24
                targetSdk = 34
            }
            create("pagseguro") {
                dimension = "providers"
                minSdk = 23
            }
            create("rede") {
                dimension = "providers"
            }
            create("getnet") {
                dimension = "providers"
                minSdk = 22
            }
            create("vero") {
                dimension = "providers"
                minSdk = 22
            }
            create("sicoob") {
                dimension = "providers"
                minSdk = 24
                targetSdk = 34
            }
            create("sitef") {
                dimension = "providers"
            }
            create("reduced") {
                dimension = "providers"
            }
            create("default") {
                dimension = "tefDevice"
            }
            create("adyen") {
                dimension = "tefDevice"
                minSdk = 28
                targetSdk = 34
            }
            create("gpos790") {
                dimension = "tefDevice"
                minSdk = 26
            }
            create("gpos760") {
                dimension = "tefDevice"
            }
            create("gpos720") {
                dimension = "tefDevice"
                minSdk = 26
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Android
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit

    if (useLocalSdk) {
        implementation "SDKPayServices:core"
        implementation "SDKPayServices:config"
        implementation "SDKPayServices:common"
        implementation "SDKPayServices:ui"
        implementation "SDKPayServices:provider"

        println("Using local SDKPayServices from ../SDKPayServices")
    } else {
        // 1. Dependências COMUNS do SDK (vão para todos os flavors)
        implementation "SDKPayServices:config:$sdkPayServicesVersion"
        implementation "SDKPayServices:common:$sdkPayServicesVersion"

        // 2. Dependências DINÂMICAS por flavor
        flavors.each { flavorName, _ ->
            add("${flavorName}Implementation", "SDKPayServices:core-${flavorName}:$sdkPayServicesVersion")
            add("${flavorName}Implementation", "SDKPayServices:${flavorName}:$sdkPayServicesVersion")
            println("Using published SDKPayServices $flavorName version $sdkPayServicesVersion")
        }
    }
}
