plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.linx.paykit.demo'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.linx.paykit.demo"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Android
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit

    // SDK Único
    implementation("SDKPayServices:core-stone:2.2.0.+")
    implementation("SDKPayServices:stone:2.2.0.+")
    implementation("SDKPayServices:config:2.2.0.+")
    implementation("SDKPayServices:common:2.2.0.+")
}