plugins {
    alias(libs.plugins.android.application)
}

def sdkPayServicesVersion = "2.2.0.+"

def flavors = [
        linxtef: 22,
        linxtefadyen: 28,
        linxtefgpos760: 22,
        linxtefgpos720: 22,
        stone: 22,
        pagseguro: 23,
        vero: 22,
        getnet: 22,
        rede: 28,
        cielo: 25,
        sicoob: 24,
        sitef: 22,
        gsurf: 26
]

android {
    namespace 'com.linx.paykit.demo'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.linx.paykit.demo"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }

    flavorDimensions "providers"
    productFlavors {
        flavors.each { flavorName, flavorMinSdk ->
            create(flavorName) {
                dimension "providers"
                minSdk flavorMinSdk
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Android
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit

    // 1. Dependências COMUNS do SDK (vão para todos os flavors)
    implementation "SDKPayServices:config:$sdkPayServicesVersion"
    implementation "SDKPayServices:common:$sdkPayServicesVersion"

    // 2. Dependências DINÂMICAS por flavor
    flavors.each { flavorName, _ ->
        add("${flavorName}Implementation", "SDKPayServices:core-${flavorName}:$sdkPayServicesVersion")
        add("${flavorName}Implementation", "SDKPayServices:${flavorName}:$sdkPayServicesVersion")
    }
}